[build]
  # Change to the directory containing your React app
  base = "pawtracker"
  command = "npm install && npm run build"
  publish = "pawtracker/build"

  # Environment variables
  [build.environment]
    NODE_VERSION = "18"

  # Redirect all requests to index.html for SPA routing
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

  ## more info on configuring this file: https://ntl.fyi/file-based-build-config
