[build]
  base = "pawtracker/"
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://pawtracker.fly.dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
