-- Fix service_dog_tasks id to auto-generate values
-- This will allow INSERTs without providing an explicit id

BEGIN;

-- Ensure the table exists
CREATE TABLE IF NOT EXISTS service_dog_tasks (
    id INTEGER PRIMARY KEY,
    pet_id INTEGER NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    task_name VARCHAR(255) NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Add identity to id column if not already present
-- Note: PostgreSQL will error if identity already exists; using DO block to guard
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns c
    JOIN information_schema.sequences s ON c.column_default LIKE ('nextval(''%"' || s.sequence_name || '"%''::regclass)')
    WHERE c.table_name = 'service_dog_tasks' AND c.column_name = 'id'
  ) THEN
    ALTER TABLE service_dog_tasks
      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

COMMIT;
